### ISSUE TITLE
Change color of icons

### ISSUE THREAD

**Issue by mameesie** [obsidian-tasks-group/obsidian-tasks-custom-icons#16]
Really appreciate this awesome plugin!

When i try to change the color for icons .tasks-postpone and .tasks-edit it will work but for .tasks-backlink it won't. Would you happen to know how to change this color without changing the color for inner links? This is my CSS:

.tasks-postpone,
.tasks-edit
.tasks-backlink
{
  color: black !important;
}

Thanks!

**Comment by replete** [comment]
![Screenshot 2024-09-30 at 10 37 53](https://github.com/user-attachments/assets/ad1a4b76-a148-4d8b-9a83-da9e6e19a3d9)
![Screenshot 2024-09-30 at 10 38 00](https://github.com/user-attachments/assets/61d515bf-0fa5-4547-9b1b-496162bce098)
