### ISSUE TITLE
Link and Edit buttons

### ISSUE THREAD

**Issue by vi-cat** [obsidian-tasks-group/obsidian-tasks-custom-icons#2]
<img width="224" alt="2023__July_19_-_Wednesday_-_Qontoer_-_Obsidian_v1_3_5" src="https://github.com/replete/obsidian-tasks-custom-icons/assets/2243885/e998be62-076a-4aae-a11f-6e382c6f1ddf">

I have enabled the Lucile css file. The Link and Edit buttons for each task is still using the old icon. How do I update them? they're breaking the vibe :)

**Comment by vi-cat** [comment]
No, I don't. The backlink object does not use `::before`:

```
<span class="tasks-backlink"><a rel="noopener" target="_blank" class="internal-link internal-link-short-mode"> 🔗</a></span>
```

And this is the edit button:

```
<a class="tasks-edit"></a>
```

**Comment by vi-cat** [comment]
After doing more investigation, I was able to have the link button render property by:

- Cloning the repo
- Running the build command
- Adding `a.internal-link` to the resulting css

```
span.tasks-list-text,
a.internal-link,
.cm-line:has(.task-list-label) [class^=cm-list-] {
    font-family: 'TasksMonoEmojis', var(--font-text);
}
```

**Comment by replete** [comment]
This would have been a nice PR, thanks for letting me know!

----- Original message -----

**Comment by replete** [comment]
Link icon was added to Lucide iconfont previously.
