### ISSUE TITLE
Add support for Cancelled emoji

### ISSUE THREAD

**Issue by GlotPoly** [obsidian-tasks-group/obsidian-tasks-custom-icons#4]
Is it possible to add the cancelled emoji (❌) to the provided CSS snippets? Especially for "Lucide-based Icon set 2".
I'm not really well versed in creating my own complete custom icon set (might try it if I have more time).

I'm unsure if this would be a lot of work but I would greatly appreciate it. It would be a great addition.

Picture for reference:
![Screenshot 2024-02-04 at 11 13 48](https://github.com/replete/obsidian-tasks-custom-icons/assets/126024497/b0dba217-cc06-4c19-bc1c-9eaecfa257f3)

**Comment by replete** [comment]
If cancelled is used by Tasks, you can do this just by adding an SVG with the correct filename and running the app again. Would be an easy PR and I'll merge it
